# -*- coding: utf-8 -*-
"""Filas atómicas de Matriz Consolidada (grano Money Me: login, registro, …)."""

SHA_I006 = "5ce7575"
SHA_I005 = "4e08b9e"
SHA_I002 = "f086a63"
SHA_I003 = "8b20337"
SHA_I004 = "f086a63"
SHA_I007 = "e9a0965"
SHA_I008 = "8b20337"
SHA_INC8 = "3394712"  # I-009 … I-017 (0.9.1 + Incremento 8)

PRES = "Presentation (React)"
API = "API (PHP)"
ML = "ML (FastAPI)"
ALTO = "Alto (integración/validación)"
MEDIO = "Medio (entrega/despliegue)"
PLAN_FN = "documents/04_testing/plan_pruebas_funcionales.md"


def F(
    id,
    modulo,
    funcion,
    capa,
    impacto,
    prompt,
    tecnica,
    resultado,
    ruta,
    archivo,
    completa,
    commit,
    test,
    obs,
    criterio="Aprobado",
    iter=0,
    test_auto="No",
):
    return {
        "id": id,
        "modulo": modulo,
        "funcion": funcion,
        "fase": "Implementación",
        "capa": capa,
        "impacto": impacto,
        "ci": "No",
        "cd": "No",
        "test_auto": test_auto,
        "monitor": "No",
        "prompt": prompt,
        "tecnica": tecnica,
        "ver_prompt": "v1",
        "iter": iter,
        "criterio": criterio,
        "resultado": resultado,
        "ruta": ruta,
        "archivo": archivo,
        "completa": completa,
        "commit": commit,
        "test": test,
        "obs": obs,
    }


FUNCIONES = [
    # --- auth ---
    F("F-001", "auth", "Inicio de sesión", PRES, ALTO, "I-006", "CoT guiado",
      "POST /auth/login emite JWT y redirige a /v2/dashboard",
      "src/features/auth/", "Login.jsx", "src/features/auth/Login.jsx", SHA_I006,
      f"{PLAN_FN} (AUTH-001)", "HU-AUTH-001. Credenciales inválidas no revelan si el usuario existe."),
    F("F-002", "auth", "Cerrar sesión", PRES, MEDIO, "I-006", "CoT guiado",
      "Navbar Salir limpia token y vuelve a /login",
      "src/components/", "Navbar.jsx", "src/components/Navbar.jsx", SHA_I006,
      f"{PLAN_FN} (AUTH-004)", "HU-AUTH-004."),
    F("F-003", "auth", "Persistencia de sesión", PRES, ALTO, "I-006", "CoT guiado",
      "F5 mantiene sesión vía AuthContext y localStorage",
      "src/context/", "AuthContext.jsx", "src/context/AuthContext.jsx", SHA_I006,
      f"{PLAN_FN} (AUTH-003)", "HU-AUTH-003."),
    F("F-004", "auth", "Protección JWT de la API", API, ALTO, "I-006", "CoT guiado",
      "Rutas V2 sin Bearer responden 401 (salvo /auth)",
      "backend/api/v2/middleware/", "AuthMiddleware.php",
      "backend/api/v2/middleware/AuthMiddleware.php", SHA_I006,
      f"{PLAN_FN} (REG-004)", "HU-AUTH-002. requireAuth en index.php."),
    F("F-005", "auth", "Autorización por rol (RBAC)", API, ALTO, "I-009", "CoT guiado",
      "Técnico en POST/PUT/DELETE /usuarios → 403",
      "backend/api/v2/middleware/", "AuthMiddleware.php",
      "backend/api/v2/middleware/AuthMiddleware.php", SHA_INC8,
      "backend/tests/AuthMiddlewareTest.php",
      "HU-AUTH-005 / HU-CFG-006. RoleRoute en UI. iter I-009.",
      iter=1, test_auto="Parcial"),
    # --- configuracion ---
    F("F-006", "configuracion", "Listado de áreas", PRES, MEDIO, "I-005", "Few-shot",
      "GET /areas alimenta Configuración e Inventario",
      "src/features/configuracion/components/", "ConfiguracionPage.jsx",
      "src/features/configuracion/components/ConfiguracionPage.jsx", SHA_I005,
      f"{PLAN_FN} (CFG-001)", "HU-CFG-001."),
    F("F-007", "configuracion", "Alta de área", PRES, MEDIO, "I-005", "Few-shot",
      "POST /areas crea el área y aparece en EquipoForm",
      "src/features/configuracion/components/", "AreaForm.jsx",
      "src/features/configuracion/components/AreaForm.jsx", SHA_I005,
      f"{PLAN_FN} (CFG-002)", "HU-CFG-002 / HU-CFG-005."),
    F("F-008", "configuracion", "Edición de área", PRES, MEDIO, "I-017", "Few-shot",
      "PUT /areas?id= actualiza nombre, jefe y gerencia",
      "src/features/configuracion/components/", "AreaForm.jsx",
      "src/features/configuracion/components/AreaForm.jsx", SHA_INC8,
      f"{PLAN_FN} (CFG-009)", "HU-CFG-007."),
    F("F-009", "configuracion", "Baja de área", API, ALTO, "I-017", "Few-shot",
      "DELETE /areas?id= 204; 409 si el área tiene equipos",
      "backend/api/v2/models/", "Area.php", "backend/api/v2/models/Area.php", SHA_INC8,
      "backend/tests/AreaTest.php",
      "HU-CFG-007. Solo Administrador.", test_auto="Parcial"),
    F("F-010", "configuracion", "Listado de personal", PRES, MEDIO, "I-005", "Few-shot",
      "GET /usuarios lista personal con rol y área",
      "src/features/configuracion/components/", "ConfiguracionPage.jsx",
      "src/features/configuracion/components/ConfiguracionPage.jsx", SHA_I005,
      f"{PLAN_FN} (CFG-003)", "HU-CFG-003."),
    F("F-011", "configuracion", "Registro de usuario", PRES, ALTO, "I-005", "Few-shot",
      "POST /usuarios crea cuenta con password BCRYPT (solo Admin)",
      "src/features/configuracion/components/", "UsuarioForm.jsx",
      "src/features/configuracion/components/UsuarioForm.jsx", SHA_I005,
      "backend/tests/UsuarioTest.php",
      "HU-CFG-004. No hay auto-registro público.", test_auto="Parcial"),
    F("F-012", "configuracion", "Edición y baja de usuario", API, ALTO, "I-009", "CoT guiado",
      "PUT/DELETE /usuarios; no autoeliminación ni borrar el último admin",
      "backend/api/v2/controllers/", "UsuarioController.php",
      "backend/api/v2/controllers/UsuarioController.php", SHA_INC8,
      "backend/tests/UsuarioTest.php",
      "HU-CFG-006. requireRole Administrador.", iter=1, test_auto="Parcial"),
    F("F-013", "configuracion", "Catálogo de gerencias", API, MEDIO, "I-017", "Few-shot",
      "CRUD /gerencias; área.gerencia_id opcional (selector, no etiqueta libre)",
      "backend/api/v2/controllers/", "GerenciaController.php",
      "backend/api/v2/controllers/GerenciaController.php", SHA_INC8,
      f"{PLAN_FN} (CFG-010)", "HU-CFG-008."),
    # --- inventario ---
    F("F-014", "inventario", "Listado de equipos", PRES, ALTO, "I-002", "Few-shot",
      "GET /equipos muestra tabla patrimonial",
      "src/features/inventario/components/", "InventarioPage.jsx",
      "src/features/inventario/components/InventarioPage.jsx", SHA_I002,
      f"{PLAN_FN} (INV-001)", "HU-INV-001."),
    F("F-015", "inventario", "Alta de equipo", PRES, ALTO, "I-002", "Few-shot",
      "POST /equipos persiste código patrimonial de 12 dígitos",
      "src/features/inventario/components/", "EquipoForm.jsx",
      "src/features/inventario/components/EquipoForm.jsx", SHA_I002,
      "src/lib/equipoTipo.test.js",
      "HU-INV-002 / HU-INV-008. RAM numérica, no texto “8 GB”.", test_auto="Parcial"),
    F("F-016", "inventario", "Edición de equipo", API, ALTO, "I-002", "Few-shot",
      "GET/PUT /equipos/{id} actualiza ficha de inventario",
      "backend/api/v2/controllers/", "EquipoController.php",
      "backend/api/v2/controllers/EquipoController.php", SHA_I002,
      f"{PLAN_FN} (INV-010)", "HU-INV-009."),
    F("F-017", "inventario", "Filtro de inventario", PRES, MEDIO, "I-004", "Few-shot",
      "Filtro de texto reduce filas en cliente",
      "src/features/inventario/components/", "InventarioPage.jsx",
      "src/features/inventario/components/InventarioPage.jsx", SHA_I004,
      f"{PLAN_FN} (INV-003)", "HU-INV-003."),
    F("F-018", "inventario", "Plantilla Excel de carga", API, MEDIO, "I-009", "CoT guiado",
      "GET /equipos/plantilla descarga .xlsx con columna color alineada",
      "backend/api/v2/controllers/", "EquipoController.php",
      "backend/api/v2/controllers/EquipoController.php", SHA_INC8,
      "backend/tests/EquipoPlantillaTest.php",
      "HU-INV-004. Fila de ejemplo no desplaza numero_serie.", iter=1, test_auto="Parcial"),
    F("F-019", "inventario", "Carga masiva Excel", API, ALTO, "I-002", "Few-shot",
      "POST /equipos/carga-masiva importa filas .xlsx",
      "backend/api/v2/controllers/", "EquipoController.php",
      "backend/api/v2/controllers/EquipoController.php", SHA_I002,
      f"{PLAN_FN} (INV-005)", "HU-INV-005."),
    F("F-020", "inventario", "Indicador de riesgo en inventario", PRES, MEDIO, "I-007", "CoT guiado",
      "Columna Riesgo ML (badge) vía predicción por lote",
      "src/features/inventario/components/", "InventarioPage.jsx",
      "src/features/inventario/components/InventarioPage.jsx", SHA_I007,
      f"{PLAN_FN} (ML-002)", "HU-INV-006 / HU-ML-002."),
    # --- ficha ---
    F("F-021", "ficha", "Búsqueda de ficha por código", PRES, ALTO, "I-003", "Few-shot",
      "GET /fichas-tecnicas/buscar/{codigo} (12 dígitos)",
      "src/features/inventario/components/", "FichaTecnicaPage.jsx",
      "src/features/inventario/components/FichaTecnicaPage.jsx", SHA_I004,
      f"{PLAN_FN} (FIC-001)", "HU-FIC-001. Vacío controlado, no 500."),
    F("F-022", "ficha", "Consulta de ficha técnica", API, ALTO, "I-003", "Few-shot",
      "GET /fichas-tecnicas/{id} devuelve hardware/software",
      "backend/api/v2/controllers/", "FichaTecnicaController.php",
      "backend/api/v2/controllers/FichaTecnicaController.php", SHA_I004,
      f"{PLAN_FN} (FIC-002)", "HU-FIC-002 / HU-INV-007."),
    F("F-023", "ficha", "Edición de evaluación técnica", PRES, ALTO, "I-003", "Few-shot",
      "PUT ficha persiste conservación, estado y observaciones",
      "src/features/inventario/components/", "FichaTecnicaPanel.jsx",
      "src/features/inventario/components/FichaTecnicaPanel.jsx", SHA_I004,
      f"{PLAN_FN} (FIC-003)", "HU-FIC-003–007."),
    F("F-024", "ficha", "Bloque predictivo en ficha", PRES, MEDIO, "I-008", "CoT guiado",
      "La ficha muestra score de riesgo si FastAPI está arriba",
      "src/features/inventario/components/", "FichaTecnicaPanel.jsx",
      "src/features/inventario/components/FichaTecnicaPanel.jsx", SHA_I008,
      f"{PLAN_FN} (FIC-008)", "HU-FIC-008. iter I-008.", iter=2),
    # --- mantenimiento ---
    F("F-025", "mantenimiento", "Timeline de mantenimientos", PRES, ALTO, "I-003", "Few-shot",
      "GET /mantenimientos lista intervenciones con categoría nombrada",
      "src/features/mantenimiento/components/", "MantenimientoPage.jsx",
      "src/features/mantenimiento/components/MantenimientoPage.jsx", SHA_I003,
      f"{PLAN_FN} (MNT-001)", "HU-MNT-001."),
    F("F-026", "mantenimiento", "Registro de intervención", PRES, ALTO, "I-003", "Few-shot",
      "POST /mantenimientos liga equipo_id; categoría obligatoria en correctivo",
      "src/features/mantenimiento/components/", "MantenimientoForm.jsx",
      "src/features/mantenimiento/components/MantenimientoForm.jsx", SHA_I003,
      f"{PLAN_FN} (MNT-002)", "HU-MNT-002 / HU-MNT-007."),
    F("F-027", "mantenimiento", "Detalle de intervención", PRES, MEDIO, "I-003", "Few-shot",
      "GET /mantenimientos/{id} abre modal de ficha de intervención",
      "src/features/mantenimiento/components/", "MantenimientoDetalleModal.jsx",
      "src/features/mantenimiento/components/MantenimientoDetalleModal.jsx", SHA_I003,
      f"{PLAN_FN} (MNT-004)", "HU-MNT-004."),
    F("F-028", "mantenimiento", "Historial por código patrimonial", API, MEDIO, "I-003", "Few-shot",
      "GET /mantenimientos/historial/{codigo} filtra timeline de un equipo",
      "backend/api/v2/controllers/", "MantenimientoController.php",
      "backend/api/v2/controllers/MantenimientoController.php", SHA_I003,
      f"{PLAN_FN} (MNT-003)", "HU-MNT-003 / HU-MNT-006."),
    F("F-029", "mantenimiento", "Sincronización de telemetría", API, ALTO, "I-008", "CoT guiado",
      "Al registrar mantenimiento se actualiza snapshot del equipo",
      "backend/api/v2/models/", "Mantenimiento.php",
      "backend/api/v2/models/Mantenimiento.php", SHA_I008,
      "backend/tests/MantenimientoTest.php",
      "HU-MNT-010. iter I-008.", iter=2, test_auto="Parcial"),
    F("F-030", "mantenimiento", "Sugerencia de categoría de falla", PRES, MEDIO, "I-007", "CoT guiado",
      "Correctivo muestra sugerencia ML si FastAPI responde",
      "src/features/mantenimiento/components/", "MantenimientoForm.jsx",
      "src/features/mantenimiento/components/MantenimientoForm.jsx", SHA_I007,
      f"{PLAN_FN} (ML-004)", "HU-MNT-009 / HU-ML-004."),
    # --- dashboard ---
    F("F-031", "dashboard", "Indicadores operativos", PRES, MEDIO, "I-006", "CoT guiado",
      "GET /dashboard pinta conteos persistidos tras el login",
      "src/features/dashboard/components/", "DashboardPage.jsx",
      "src/features/dashboard/components/DashboardPage.jsx", SHA_I006,
      f"{PLAN_FN} (DSH-001)", "HU-DSH-001–004."),
    F("F-032", "dashboard", "Alertas predictivas", PRES, MEDIO, "I-007", "CoT guiado",
      "GET /ml/alertas lista top de riesgo; vacío/N/A si ML caído",
      "src/features/dashboard/components/", "DashboardPage.jsx",
      "src/features/dashboard/components/DashboardPage.jsx", SHA_I007,
      f"{PLAN_FN} (ML-001)", "HU-ML-001 / HU-ML-005."),
    F("F-033", "dashboard", "Consulta de equipos por etiquetas", API, MEDIO, "I-008", "CoT guiado",
      "GET /dashboard/consulta filtra tipo, estado y tipo_otro",
      "backend/api/v2/controllers/", "DashboardController.php",
      "backend/api/v2/controllers/DashboardController.php", SHA_I008,
      "backend/tests/DashboardConsultaTest.php",
      "HU-DSH-005 / HU-DSH-006.", test_auto="Parcial"),
    # --- ml ---
    F("F-034", "ml", "Predicción de riesgo (un equipo)", ML, ALTO, "I-007", "CoT guiado",
      "POST /predict/riesgo devuelve score; proxy JWT /api/v2/ml/*",
      "ml/app/", "main.py", "ml/app/main.py", SHA_I007,
      "ml/tests/test_ml_schemas.py",
      "HU-ML-002.", test_auto="Parcial"),
    F("F-035", "ml", "Predicción de riesgo (lote)", ML, ALTO, "I-007", "CoT guiado",
      "Batch JSON {} (no []); límite acotado",
      "ml/app/", "main.py", "ml/app/main.py", SHA_I007,
      "ml/tests/test_ml_schemas.py",
      "HU-INV-006. iter ≥2 (batch [] vs {}).", iter=2, test_auto="Parcial"),
    F("F-036", "ml", "Degradación si FastAPI no responde", API, ALTO, "I-007", "CoT guiado",
      "Inventario y login siguen; alertas N/A (ADR-002)",
      "backend/api/v2/controllers/", "MlController.php",
      "backend/api/v2/controllers/MlController.php", SHA_I007,
      f"{PLAN_FN} (ML-003 / DEG-001)", "HU-ML-005.", iter=2),
    F("F-037", "ml", "Reentrenamiento del modelo", ML, MEDIO, "I-007", "CoT guiado",
      "POST /ml/train (Admin); artefacto riesgo_equipo_v2.joblib",
      "ml/app/", "main.py", "ml/app/main.py", SHA_I007,
      "ml/tests/test_features.py",
      "HU-ML-003. Features telemetría I-008.", test_auto="Parcial"),
    # --- reportes ---
    F("F-038", "reportes", "PDF de ficha de equipo", API, MEDIO, "I-004", "Zero-shot + few-shot",
      "GET /reportes/equipo/{id} genera PDF con código patrimonial",
      "backend/api/v2/controllers/", "ReporteController.php",
      "backend/api/v2/controllers/ReporteController.php", SHA_I004,
      f"{PLAN_FN} (RPT-001)", "HU-RPT-001 / HU-FIC-005."),
    F("F-039", "reportes", "PDF de historial de mantenimiento", API, MEDIO, "I-004", "Few-shot",
      "GET /reportes/mantenimiento/historial/{codigo} descarga PDF",
      "backend/api/v2/controllers/", "ReporteController.php",
      "backend/api/v2/controllers/ReporteController.php", SHA_I003,
      f"{PLAN_FN} (RPT-002)", "HU-RPT-002 / HU-MNT-005."),
    F("F-040", "reportes", "PDF de detalle de intervención", API, MEDIO, "I-004", "Few-shot",
      "GET /reportes/mantenimiento/{id} descarga PDF de la ficha",
      "backend/api/v2/controllers/", "ReporteController.php",
      "backend/api/v2/controllers/ReporteController.php", SHA_I003,
      f"{PLAN_FN} (RPT-003)", "HU-RPT-003."),
    F("F-041", "reportes", "Descarga PDF autenticada (JWT)", PRES, ALTO, "I-006", "CoT guiado",
      "downloadPdf usa blob + Authorization; no window.open anónimo",
      "src/lib/", "api.js", "src/lib/api.js", SHA_I006,
      f"{PLAN_FN} (RPT-004)", "HU-RPT-004. iter blob.", iter=1),
    F("F-042", "reportes", "PDF de cronograma (matriz A4)", API, ALTO, "I-016", "Few-shot",
      "GET /reportes/cronograma/{id} A4 L–V, 2 meses/hoja, Xn y HORA PROGRAMADA con borde",
      "backend/api/v2/controllers/", "ReporteController.php",
      "backend/api/v2/controllers/ReporteController.php", SHA_INC8,
      "backend/tests/CronogramaTest.php",
      "HU-CRN-004. Cadena I-012…I-016.", iter=2, test_auto="Parcial"),
    # --- cronograma ---
    F("F-043", "cronograma", "Menú e historial de cronogramas", PRES, ALTO, "I-010", "Few-shot",
      "Navbar «Cronograma»; GET /cronogramas lista planes (varios por año)",
      "src/features/cronograma/components/", "CronogramaListPage.jsx",
      "src/features/cronograma/components/CronogramaListPage.jsx", SHA_INC8,
      f"{PLAN_FN} (CRN-001 / CRN-008)", "HU-CRN-007 / HU-CRN-008."),
    F("F-044", "cronograma", "Alta de cronograma", PRES, ALTO, "I-010", "Few-shot",
      "POST /cronogramas {anio, nombre} crea documento; practicante 403",
      "src/features/cronograma/components/", "CronogramaListPage.jsx",
      "src/features/cronograma/components/CronogramaListPage.jsx", SHA_INC8,
      "backend/tests/CronogramaTest.php",
      "HU-CRN-009.", test_auto="Parcial"),
    F("F-045", "cronograma", "Marcado Xn por día", PRES, ALTO, "I-014", "Few-shot",
      "POST celdas {cantidad}; una columna/día; selector X1…Xn (PC+laptop)",
      "src/features/cronograma/components/", "CronogramaCantidadPopover.jsx",
      "src/features/cronograma/components/CronogramaCantidadPopover.jsx", SHA_INC8,
      "src/features/cronograma/utils/cronogramaUtils.test.js",
      "HU-CRN-001–003 / HU-CRN-013. No turnos mañana/tarde.", iter=1, test_auto="Parcial"),
    F("F-046", "cronograma", "Liberar o cambiar cantidad", PRES, ALTO, "I-014", "Few-shot",
      "cantidad 0 o DELETE de celda libera el asiento",
      "src/features/cronograma/components/", "CronogramaMatrizPage.jsx",
      "src/features/cronograma/components/CronogramaMatrizPage.jsx", SHA_INC8,
      f"{PLAN_FN} (CRN-003)", "HU-CRN-003."),
    F("F-047", "cronograma", "Totales de equipos en matriz", PRES, MEDIO, "I-011", "Few-shot",
      "Columna Tot, pie Subtotal PC/Lap/Imp y Total equipos",
      "src/features/cronograma/components/", "CronogramaMatrizPage.jsx",
      "src/features/cronograma/components/CronogramaMatrizPage.jsx", SHA_INC8,
      f"{PLAN_FN} (CRN-010)", "HU-CRN-010."),
    F("F-048", "cronograma", "Personal en HORA PROGRAMADA", PRES, MEDIO, "I-013", "Few-shot",
      "PUT /cronogramas/{id}/personal; recuadro de personas (no bienes)",
      "src/features/cronograma/components/", "CronogramaPersonalPanel.jsx",
      "src/features/cronograma/components/CronogramaPersonalPanel.jsx", SHA_INC8,
      f"{PLAN_FN} (CRN-012)", "HU-CRN-011 residual horarios; I-013 personas."),
    F("F-049", "cronograma", "Baja de cronograma", API, MEDIO, "I-015", "Few-shot",
      "DELETE /cronogramas/{id} CASCADE; practicante 403",
      "backend/api/v2/controllers/", "CronogramaController.php",
      "backend/api/v2/controllers/CronogramaController.php", SHA_INC8,
      "backend/tests/CronogramaTest.php",
      "HU-CRN-014.", test_auto="Parcial"),
    F("F-050", "cronograma", "Bandas de gerencia", PRES, MEDIO, "I-017", "Few-shot",
      "Matriz y PDF agrupan áreas bajo fila banda (sin Xn)",
      "src/features/cronograma/components/", "CronogramaMatrizPage.jsx",
      "src/features/cronograma/components/CronogramaMatrizPage.jsx", SHA_INC8,
      "backend/tests/CronogramaTest.php",
      "HU-CRN-015. Sin asignaciones no hay bandas.", test_auto="Parcial"),
    F("F-051", "cronograma", "Cobertura del mínimo anual", API, MEDIO, "I-010", "Few-shot",
      "GET matriz/cobertura: áreas cuya suma Xn no cubre PC+laptop",
      "backend/api/v2/models/", "Cronograma.php",
      "backend/api/v2/models/Cronograma.php", SHA_INC8,
      f"{PLAN_FN} (CRN-006)", "HU-CRN-005 / HU-CRN-006. SIGA/SAF = área."),
]
